### ISSUE TITLE
Installation Problem 

### ISSUE THREAD

**Issue by jahbini** [mistralai/mistral-src#124]
I am stuck at the point of pip's refusal to install the requirements.txt (unchanged from the current repository)
[requirements.txt](https://github.com/mistralai/mistral-src/files/14251164/requirements.txt)
` pip --debug install -r requirements.txt >1.log 2>2.log` results in this:
[1.log](https://github.com/mistralai/mistral-src/files/14251181/1.log)
 and stderr says:
[2.log](https://github.com/mistralai/mistral-src/files/14251184/2.log)

I'm on an 8G MacBook Pro with OS Sonoma 14.2.1

**Comment by JulienMT** [comment]
Hi, i have the same problem on Windows 11, it crash on installing xformers that is not finding torch, but it is installed and available, don't know how to correct this xformers problem

`Collecting xformers==0.0.21
  Downloading xformers-0.0.21.tar.gz (22.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.3/22.3 MB 7.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.752.0_x64__qbz5n2kfra8p0\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.752.0_x64__qbz5n2kfra8p0\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.752.0_x64__qbz5n2kfra8p0\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\money\AppData\Local\Temp\pip-build-env-tschzoch\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\money\AppData\Local\Temp\pip-build-env-tschzoch\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\money\AppData\Local\Temp\pip-build-env-tschzoch\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\money\AppData\Local\Temp\pip-build-env-tschzoch\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 23, in <module>
      ModuleNotFoundError: No module named 'torch'
      [end of output]`

**Comment by Raphael2b3** [comment]
do you have an extra GPU?

**Comment by juliendenize** [comment]
Hi! We're archiving this repository as it's no longer actively maintained, and therefore this issue is being closed.
