### ISSUE TITLE
Error on run main 

### ISSUE THREAD

**Issue by lrx1213** [mistralai/mistral-src#50]
Command： python -m main interactive /mistral-7B-v0.1/
Error:

Prompt: Hello
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/mistral/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/anaconda3/envs/mistral/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/media/cfs/lizongshang/work/deep_learning/llm/mistral/main.py", line 140, in <module>
    fire.Fire({
  File "/usr/local/anaconda3/envs/mistral/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/anaconda3/envs/mistral/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/anaconda3/envs/mistral/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/media/cfs/lizongshang/work/deep_learning/llm/mistral/main.py", line 110, in interactive
    res, _logprobs = generate(
  File "/usr/local/anaconda3/envs/mistral/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/media/cfs/lizongshang/work/deep_learning/llm/mistral/main.py", line 61, in generate
    prelogits = model.forward(
  File "/media/cfs/lizongshang/work/deep_learning/llm/mistral/mistral/model.py", line 204, in forward
    input_metadata = cache.get_input_metadata(seqlens)
  File "/media/cfs/lizongshang/work/deep_learning/llm/mistral/mistral/cache.py", line 192, in get_input_metadata
    mask = BlockDiagonalCausalMask.from_seqlens(seqlens).make_local_attention(self.sliding_window)
AttributeError: 'BlockDiagonalCausalMask' object has no attribute 'make_local_attention'

**Comment by AkashGhosh** [comment]
Can anyone know the solution to it?

**Comment by juliendenize** [comment]
Hi! We're archiving this repository as it's no longer actively maintained, and therefore this issue is being closed.
